import Head from 'next/head'
import {Typography} from "@mui/material";
import Welcome from "../components/Welcome";

export default function Home() {
  return <>
    <Head>
      <title>Home title</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <Typography variant="h1" component="h1">
      Home Page
    </Typography>
    <Welcome/>
  </>
}
