import Head from "next/head";
import {Typography} from "@mui/material";
import UsersList from "../components/UsersList";

export default function Users() {
    return <>
        <Head>
            <title>Users title</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <Typography variant="h1" component="h1">
            Users Page
        </Typography>
        <UsersList/>
    </>
}
