import Head from "next/head";
import {Typography} from "@mui/material";

export default function User() {
    return <>
        <Head>
            <title>User title</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <Typography variant="h1" component="h1">
            User Page
        </Typography>
    </>
}
